const mineflayer = require('mineflayer');
const chalk = require('chalk');

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

function createBot(account, config) {
    return new Promise((resolve, reject) => {
        const serverConfig = config.server;

        const bot = mineflayer.createBot({
            host: serverConfig.host,
            port: serverConfig.port,
            username: account.username,
            auth: serverConfig.auth || 'offline',
            version: serverConfig.version || false,
            checkTimeoutInterval: 60000
        });

        let loginConfirmed = false;
        let isDead = false;
        let kickReason = null;
        let autoGeneratedPassword = false;

        // Auto-generate a password if none is provided (6b6t requires register/login even for offline mode)
        const password = account.password && account.password.trim()
            ? account.password.trim()
            : (() => {
                autoGeneratedPassword = true;
                return Math.random().toString(36).slice(2, 10);
            })();

        if (autoGeneratedPassword) {
            console.log(chalk.yellow(`[Auth] Nessuna password configurata, ne genero una automaticamente: ${password}`));
            console.log(chalk.yellow('[Auth] Salva questa password! Il bot la userà per /register e /login.'));
        }

        bot.on('spawn', () => {
            if (isDead || loginConfirmed) return;
            console.log(chalk.cyan('[Auth] Spawn nella stanza di login.'));

            console.log(chalk.cyan('[Auth] Tentativo /register...'));
            bot.chat(`/register ${password}`);
            sleep(1500).then(() => {
                if (!loginConfirmed && !isDead) {
                    console.log(chalk.cyan('[Auth] Tentativo /login...'));
                    bot.chat(`/login ${password}`);
                }
            });
        });

        bot.on('messagestr', (message) => {
            if (isDead) return;
            const msg = message.toLowerCase();

            // EnderDash verification detected
            if (msg.includes('enderdash') || msg.includes('verify') || msg.includes('capcha') || msg.includes('captcha')) {
                console.log(chalk.red('[Auth] Rilevata verifica EnderDash!'));
                console.log(chalk.red(`[Auth] Messaggio: ${message}`));
                console.log(chalk.yellow('[Auth] Apri il link di verifica nel browser per completare l\'accesso.'));
                return;
            }

            // Login/register success detection
            if (!loginConfirmed) {
                // Confirm login only on actual success messages
                if (msg.includes('logged in') ||
                    msg.includes('login successful') ||
                    msg.includes('successfully registered')) {
                    loginConfirmed = true;
                    console.log(chalk.green('[Auth] Login confermato!'));
                    resolve(bot);
                }
            }
        });

        bot.on('error', (err) => {
            console.error(chalk.red(`[Auth] Errore: ${err.message}`));
        });

        bot.on('kicked', (reason) => {
            if (isDead) return;
            isDead = true;
            kickReason = typeof reason === 'string' ? reason : JSON.stringify(reason);
            console.log(chalk.red(`[Auth] Kickato: ${kickReason}`));

            // Try to extract verification URL for EnderDash
            const match = kickReason.match(/https?:\/\/[^\s]+/);
            if (match) {
                console.log(chalk.yellow(`[Auth] Link di verifica trovato: ${match[0]}`));
            }
        });

        bot.on('end', () => {
            console.log(chalk.red('[Auth] Disconnesso.'));
            if (!loginConfirmed) {
                reject(new Error(kickReason || 'Disconnesso prima del login'));
            }
        });

        // Timeout that triggers if we never get a login confirmation or entity
        setTimeout(() => {
            if (!loginConfirmed && !isDead) {
                isDead = true;
                reject(new Error(kickReason || 'Timeout: login non completato entro 30 secondi'));
            }
        }, 30000);
    });
}

module.exports = { createBot };
